BASE_URL = "https://tobeto.com/"
LOGIN_URL= "https://tobeto.com/giris"
PLATFORM_URL= "https://tobeto.com/platform"

home_signup_button_id="/html/body/div[1]/div/section[1]/nav/div/div/a[2]"
name_input_id="firstName"
lastName_input_id="lastName"
email_input_id="email"
password_input_id="password"
password_again_input_id="passwordAgain"
signup_button_id="/html//div[@id='__next']/div[@class='bg-front-dark bg-front-width']/main[@class='bg-front-dark']/section//button[.='Kayıt Ol']"
checkbox1_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']/div[@class='modal-content']//input[@name='contact']"
checkbox2_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']/div[@class='modal-content']//input[@name='membershipContrat']"
checkbox3_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']/div[@class='modal-content']//input[@name='emailConfirmation']"
checkbox4_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']/div[@class='modal-content']//input[@name='phoneConfirmation']"
telephone_id="/html//input[@id='phoneNumber']"
continue_button_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']//button[@class='btn btn-yes my-3']"
activationMessage_id="//div[@id='__next']/div[@class='bg-front-dark bg-front-width']/main/section//div[@class='row']/div/div/span[@class='success-payment-text']"
# activation_message_text="//div[@id='__next']/div[@class='bg-front-dark bg-front-width']/main/section//div[@class='row']/div/div/span[@class='success-payment-text']"
activation_message_text="Tobeto Platform'a kaydınız başarıyla gerçekleşti."

email_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/input[1]"
password_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/input[2]"
login_button_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"

# <---------my competences ----->

# email = "mihraa777@gmail.com"
# password="123456"
login_input_button = "/html/body/div[1]/div/section[1]/nav/div/div/a[1]"
my_competences_xpath = "/html//div[@id='__next']/div[@class='back-white']/main/section//div[@class='col-12 col-lg-3 mb-8 mb-lg-0']/div/a[4]/span[@class='sidebar-text']"
# profile_page ="/html/body/div[1]/div/nav/div[1]/ul/li[2]/a"
my_profile_edit= ".cv-edit-icon"
my_profile_page = "//div[@id='__next']//nav//ul[@class='d-none d-xxl-flex navbar-nav']/li[2]/a[@href='#']"
alert_login_text ="//div[@id='__next']/div[@class='back-white']//div[@role='alert']//button[@type='button']"
alert_competency_not_added = "//div[@id='__next']//div[@role='alert']/div[@class='toast-body']"
section_competence = "/html/body/div[1]/div/main/section/div/div/div[2]/div[1]/div/div/div/div[1]/div[2]"
save_competence_button = "/html/body/div[1]/div/main/section/div/div/div[2]/button"
delete_competence_icon = "#__next > div > main > section > div > div > div.col-12.col-lg-9 > div.col-12 > div:nth-child(1) > div > span"
delete_competence_choose_button = "body > div.fade.alert-modal.modal.show > div > div"
alert_competence_deleted = "alert_competence_deleted"
alert_competence_added="div[role='alert'] > .toast-body"
yes_button_id = "body > div.fade.alert-modal.modal.show > div > div > div > div > div > div.alert-buttons > button.btn.btn-yes.my-3"

competence_see_icon ="#__next > div > main > div > div:nth-child(2) > div.col-md-4.col-12 > div > div:nth-child(3) > div > div.cv-box-header > div > span.cv-see-icon"

#Certificates
my_certificates_xpath= "//*[@id='__next']/div/main/section/div/div/div[1]/div/a[5]"
certificates_file_input ="//*[@id='__next']/div/main/section/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div"
certificate_browse_button ="#__next > div > main > section > div > div > div.col-12.col-lg-9 > div > div:nth-child(2) > div > div.col-12.tobeto-light-bg > div > div:nth-child(3) > div > div > div > div.uppy-Dashboard-inner > div > div.uppy-Dashboard-AddFiles > div.uppy-Dashboard-AddFiles-title > button"
certificates_file_load="#__next > div > main > section > div > div > div.col-12.col-lg-9 > div > div:nth-child(2) > div > div.col-12.tobeto-light-bg > div"
certificate_delete_icon="#__next > div > main > section > div > div > div.col-12.col-lg-9 > div > div:nth-child(2) > div > div.table-responsive-sm > table > tbody > tr > td:nth-child(4) > span.trashIcon"
certificates_download_icon="#__next > div > main > section > div > div > div.col-12.col-lg-9 > div > div:nth-child(2) > div > div.table-responsive-sm > table > tbody > tr > td:nth-child(4) > span.fileIcon"
file_path="C:\Users\tubabezek\Desktop\Certificates"
yes_button_certificate ="body > div.fade.alert-modal.modal.show > div > div > div > div > div > div.alert-buttons > button.btn.btn-yes.my-3"
certificate_choose_button= "/html/body/div[3]/div/div"
alert_certificate_deleted="div[role='alert'] > .toast-body"


