BASE_URL="https://tobeto.com/"
BASE_URL="https://tobeto.com/"
home_signup_button_id="/html/body/div[1]/div/section[1]/nav/div/div/a[2]"
name_input_id="firstName"
lastName_input_id="lastName"
email_input_id="email"
password_input_id="password"
password_again_input_id="passwordAgain"
signup_button_id="/html//div[@id='__next']/div[@class='bg-front-dark bg-front-width']/main[@class='bg-front-dark']/section//button[.='Kayıt Ol']"
checkbox1_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']/div[@class='modal-content']//input[@name='contact']"
checkbox2_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']/div[@class='modal-content']//input[@name='membershipContrat']"
checkbox3_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']/div[@class='modal-content']//input[@name='emailConfirmation']"
checkbox4_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']/div[@class='modal-content']//input[@name='phoneConfirmation']"
telephone_id="/html//input[@id='phoneNumber']"
continue_button_id="/html/body/div[@role='dialog']/div[@class='modal-dialog modal-dialog-centered']//button[@class='btn btn-yes my-3']"
activationMessage_id="//div[@id='__next']/div[@class='bg-front-dark bg-front-width']/main/section//div[@class='row']/div/div/span[@class='success-payment-text']"
# activation_message_text="//div[@id='__next']/div[@class='bg-front-dark bg-front-width']/main/section//div[@class='row']/div/div/span[@class='success-payment-text']"
activation_message_text="Tobeto Platform'a kaydınız başarıyla gerçekleşti."