base_url = "https://tobeto.com/giris"
email_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/input[1]"
password_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/input[2]"
login_button_xpath = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
announcementAndNewsButton_xpath = "//button[@id='notification-tab']"
showMoreButton_xpath = "//*[@id='notification-tab-pane']/div/div[4]"
oneAnnouncement_css = "[class='col-md-4 col-12 my-4']"
callButton_xpath = "/html//input[@id='search']"
newsView_xpath = "//*[@id='notification-tab-pane']/div"
typeButton_xpath = "/html//div[@id='__next']/div[@class='back-white']/main/div[@class='container']//div[@class='dropdown']/button[@type='button']"
announcementbutton_xpath = "/html//input[@id='typeAnnouncement']"
organizationButton_xpath = "/html//div[@id='__next']/div[@class='back-white']/main/div[@class='container']/div[1]/div/div[3]/div[1]/div[1]/div[2]"
istanbulIsCodingButton_xpath = "//div[@id='react-select-2-option-0']"
istanbulIsCodingButtonKaldir_css = "div[role='button'] > .css-8mmkcg"
arrangementButton_xpath = "/html//div[@id='__next']/div[@class='back-white']/main/div[@class='container']/div[1]/div/div[4]/div[1]/button[@type='button']"
newToOld_xpath = "/html//div[@id='__next']/div[@class='back-white']/main/div[@class='container']//ul[@class='dropdown-menu new-filter show']//a[.='Tarihe Göre (Y-E)']"
oldToNew_xpath = "/html//div[@id='__next']/div[@class='back-white']/main/div[@class='container']//ul[@class='dropdown-menu new-filter show']//a[.='Tarihe Göre (E-Y)']"
hideReadWhatButton_xpath = "/html//div[@id='__next']/div[@class='back-white']/main/div[@class='container']//button[@class='read-hide']"
showAllButton_xpath = "/html//div[@id='__next']/div[@class='back-white']/main/div[@class='container']//button[@class='read-show']"
